// SPDX-FileCopyrightText: 2026 Nikoloz Demetrashvili
// SPDX-License-Identifier: Apache-2.0
//
// Generated by chip/gen_e2_rtl.py from chip/OBSERVABILITY.json.
// Do not edit. NOT SIMULATED: lint and gate-level test in the build.
//
// Three arms of 16. Arm A is auto-placed ro_macro, Arm C is ro_armc
// under placement constraints, Arm B is the external hardened macro
// bank reached through armb_en and armb_out.

`timescale 1ps/1ps
`default_nettype none

module ro_puf_core #(
    parameter integer N_PER_ARM = 16,
    parameter integer SEL_W     = 6,
    parameter integer CNT_W     = 16
) (
    input  wire                 xclk,
    input  wire                 rst_n,
    input  wire                 start,
    input  wire [SEL_W-1:0]     ro_sel,
    input  wire [1:0]           win_sel,
    output wire [N_PER_ARM-1:0] armb_en,
    input  wire [N_PER_ARM-1:0] armb_out,
    output reg                  done,
    output wire                 active,
    output reg                  overflow,
    output wire [CNT_W-1:0]     count_out
);
    localparam integer N_RO = 3 * N_PER_ARM;

    // The four preregistered window lengths, in xclk cycles. Three
    // are safe at every corner; the last overflows at every corner
    // on purpose, so the sticky flag can be tested on any die.
    localparam [CNT_W-1:0] WIN0 = 16'd256;
    localparam [CNT_W-1:0] WIN1 = 16'd512;
    localparam [CNT_W-1:0] WIN2 = 16'd2048;
    localparam [CNT_W-1:0] WIN3 = 16'd16384;

    reg  [CNT_W-1:0] window;
    always @(*) begin
        case (win_sel)
            2'd0:    window = WIN0;
            2'd1:    window = WIN1;
            2'd2:    window = WIN2;
            2'd3:    window = WIN3;
            default: window = WIN0;
        endcase
    end

    reg             en_window;
    reg [CNT_W-1:0] wtimer;
    reg [SEL_W-1:0] active_sel;

    assign active = en_window;

    // Arm A, auto-placed. Arm C, the same circuit under placement
    // equalization. Only the selected oscillator runs, and only
    // while the window is open.
    wire [N_PER_ARM-1:0] roa_out;
    wire [N_PER_ARM-1:0] roc_out;
    genvar i;
    generate
        for (i = 0; i < N_PER_ARM; i = i + 1) begin : g_ro_bank
            ro_macro #(.IDX(i)) u_ro (
                .en (en_window & (active_sel == i[SEL_W-1:0])),
                .out(roa_out[i]));
        end
        for (i = 0; i < N_PER_ARM; i = i + 1) begin : g_ro_armc
            ro_armc #(.IDX(i)) u_ro (
                .en (en_window & (active_sel == (i + 2 * N_PER_ARM)[SEL_W-1:0])),
                .out(roc_out[i]));
        end
        for (i = 0; i < N_PER_ARM; i = i + 1) begin : g_ro_armb
            assign armb_en[i] = en_window & (active_sel == (i + N_PER_ARM)[SEL_W-1:0]);
        end
    endgenerate

    wire [2:0] arm_hot = {active_sel >= 2 * N_PER_ARM,
                          (active_sel >= N_PER_ARM) & (active_sel < 2 * N_PER_ARM),
                          active_sel < N_PER_ARM};
    wire [3:0] idx = active_sel[3:0];
    wire sel_ro = (arm_hot[0] & roa_out[idx])
                | (arm_hot[1] & armb_out[idx])
                | (arm_hot[2] & roc_out[idx]);

    always @(posedge xclk or negedge rst_n) begin
        if (!rst_n) begin
            en_window  <= 1'b0;
            wtimer     <= {CNT_W{1'b0}};
            done       <= 1'b0;
            active_sel <= {SEL_W{1'b0}};
        end else if (start) begin
            en_window  <= 1'b1;
            wtimer     <= {CNT_W{1'b0}};
            done       <= 1'b0;
            active_sel <= ro_sel;
        end else if (en_window) begin
            if (wtimer == window) begin
                en_window <= 1'b0;
                done      <= 1'b1;
            end else begin
                wtimer <= wtimer + 1'b1;
            end
        end
    end

    wire gated_ro  = sel_ro & en_window;
    wire cnt_rst_n = rst_n & ~start;

    // Asynchronous ripple counter, one toggle flip-flop a bit, each
    // clocked by the previous stage's inverted output. Built bit by
    // bit so every flip-flop keeps a single driver, which the linter
    // requires.
    wire [CNT_W-1:0] cnt;
    wire [CNT_W:0]   tff_clk;
    assign tff_clk[0] = gated_ro;

    genvar b;
    generate
        for (b = 0; b < CNT_W; b = b + 1) begin : g_ripple
            reg q;
            always @(posedge tff_clk[b] or negedge cnt_rst_n)
                if (!cnt_rst_n) q <= 1'b0;
                else            q <= ~q;
            assign cnt[b]       = q;
            assign tff_clk[b+1] = ~q;
        end
    endgenerate

    assign count_out = cnt;

    // Sticky overflow. tff_clk[CNT_W] is the carry out of the top
    // bit, so its rising edge is the wrap. Set only, cleared by
    // reset alone, so a wrap anywhere in a batch is still readable
    // after the batch.
    always @(posedge tff_clk[CNT_W] or negedge rst_n) begin
        if (!rst_n) overflow <= 1'b0;
        else        overflow <= 1'b1;
    end
endmodule

`default_nettype wire
