// SPDX-FileCopyrightText: 2026 Nikoloz Demetrashvili
// SPDX-License-Identifier: Apache-2.0
//
// Generated by chip/gen_e2_rtl.py. Do not edit. NOT SIMULATED.
//
// Three-arm RO-PUF top. arm picks the arm and ro_idx the oscillator
// inside it, so ro_sel is {arm, ro_idx} and arm is two bits now.

`timescale 1ps/1ps
`default_nettype none

module ro_puf #(
    parameter integer N_PER_ARM = 16,
    parameter integer CNT_W     = 16
) (
    input  wire                 xclk,
    input  wire                 rst_n,
    input  wire                 start,
    input  wire [1:0]           arm,
    input  wire [3:0]           ro_idx,
    input  wire [1:0]           win_sel,
    output wire [N_PER_ARM-1:0] armb_en,
    input  wire [N_PER_ARM-1:0] armb_out,
    output wire                 done,
    output wire                 active,
    output wire                 overflow,
    output wire [CNT_W-1:0]     count_out
);
    localparam integer SEL_W = 6;

    wire [SEL_W-1:0] ro_sel = {arm, ro_idx};

    ro_puf_core #(.N_PER_ARM(N_PER_ARM), .SEL_W(SEL_W), .CNT_W(CNT_W)) u_core (
        .xclk     (xclk),
        .rst_n    (rst_n),
        .start    (start),
        .ro_sel   (ro_sel),
        .win_sel  (win_sel),
        .armb_en  (armb_en),
        .armb_out (armb_out),
        .done     (done),
        .active   (active),
        .overflow (overflow),
        .count_out(count_out));
endmodule

`default_nettype wire
