// SPDX-FileCopyrightText: 2026 Nikoloz Demetrashvili
// SPDX-License-Identifier: Apache-2.0
//
// Generated by chip/gen_e2_rtl.py from chip/OBSERVABILITY.json.
// Do not edit. NOT SIMULATED.
//
// Pin map, which is the spec's and not a copy of it:
//   ui [0] in  start
//   ui [1] in  arm select bit 0
//   ui [2] in  ro_idx[0]
//   ui [3] in  ro_idx[1]
//   ui [4] in  ro_idx[2]
//   ui [5] in  ro_idx[3]
//   ui [6] in  readout byte select
//   ui [7] in  arm select bit 1
//   uio[0] out done
//   uio[1] in  window select bit 0
//   uio[2] in  window select bit 1
//   uio[3] in  read version instead of count
//   uio[4] out counter overflowed, sticky
//   uio[5] out measurement active
//   uio[6] in  reserved
//   uio[7] in  reserved
//   uio_oe = 0x31

`timescale 1ps/1ps
`default_nettype none

module tt_um_nikodemetrashvili20_ro_puf (
    input  wire [7:0] ui_in,
    output wire [7:0] uo_out,
    input  wire [7:0] uio_in,
    output wire [7:0] uio_out,
    output wire [7:0] uio_oe,
    input  wire       ena,
    input  wire       clk,
    input  wire       rst_n
);
    localparam [7:0] PROTOCOL_VERSION = 8'd2;
    localparam [7:0] BUILD_ID         = 8'h1A;

    wire [1:0] arm      = {ui_in[7], ui_in[1]};
    wire [3:0] ro_idx   = ui_in[5:2];
    wire       byte_sel = ui_in[6];
    wire [1:0] win_sel  = {uio_in[2], uio_in[1]};
    wire       rd_ver   = uio_in[3];

    // One-cycle start pulse from the rising edge of ui_in[0], so a
    // slow write that holds the pin high still starts one run.
    reg start_d;
    always @(posedge clk or negedge rst_n)
        if (!rst_n) start_d <= 1'b0;
        else        start_d <= ui_in[0];
    wire start_pulse = ui_in[0] & ~start_d;

    wire        done;
    wire        active;
    wire        overflow;
    wire [15:0] count;
    wire [15:0] armb_en;
    wire [15:0] armb_out;

    ro_puf #(.N_PER_ARM(16), .CNT_W(16)) u_puf (
        .xclk     (clk),
        .rst_n    (rst_n),
        .start    (start_pulse),
        .arm      (arm),
        .ro_idx   (ro_idx),
        .win_sel  (win_sel),
        .armb_en  (armb_en),
        .armb_out (armb_out),
        .done     (done),
        .active   (active),
        .overflow (overflow),
        .count_out(count));

    wire [7:0] count_byte = byte_sel ? count[15:8] : count[7:0];
    wire [7:0] ver_byte   = byte_sel ? BUILD_ID : PROTOCOL_VERSION;
    assign uo_out = rd_ver ? ver_byte : count_byte;

    assign uio_out = {1'b0, 1'b0, active, overflow, 1'b0, 1'b0, 1'b0, done};
    assign uio_oe  = 8'h31;

    // Tie off what nothing reads, so the linter stays quiet.
    wire _unused = &{ena, uio_in[0], uio_in[7:4], 1'b0};
endmodule

`default_nettype wire
