// SPDX-FileCopyrightText: 2026 Nikoloz Demetrashvili
// SPDX-License-Identifier: Apache-2.0
//
// Arm C ring oscillator. Generated by chip/gen_armc.py, do not edit.
//
// The same circuit as dualarm/src/ro_macro.v, node for node: an enable NAND,
// 30 inverters and an output buffer tapped halfway along the chain. It
// carries its own module name so that synthesis keeps the two arms separate,
// and its own `keep` attributes so the optimiser cannot merge a stage away.
// The treatment that makes it Arm C is not in this file, it is the placement
// constraint in armc_place.tcl. chip/lint_rtl.py R08 compares the two rings
// as netlists rather than as text and fails if they ever drift apart.
//
// NOT SIMULATED. Lint and gate-level test it in the build step.

`timescale 1ps/1ps
`default_nettype none

module ro_armc #(
    parameter integer N_INV = 30,
    parameter integer IDX   = 0
) (
    input  wire en,
    output wire out
);
    (* keep *) wire [N_INV:0] n;

    (* keep *) sky130_fd_sc_hd__nand2_1 u_nand (
        .A(en), .B(n[N_INV]), .Y(n[0]));

    genvar i;
    generate
        for (i = 0; i < N_INV; i = i + 1) begin : g_inv
            (* keep *) sky130_fd_sc_hd__inv_1 u_inv (
                .A(n[i]), .Y(n[i+1]));
        end
    endgenerate

    // Tapped mid-chain, the same node ro_macro.v taps.
    (* keep *) sky130_fd_sc_hd__buf_1 u_buf (.A(n[N_INV/2]), .X(out));
endmodule

`default_nettype wire
