#!/usr/bin/env python3
# SPDX-License-Identifier: Apache-2.0
"""
SILICON go/no-go : generate ngspice decks from the ROUTED design.

Two combined nominal-cell decks, each with all 32 ring-oscillator logical
topologies (enable NAND -> 30 inverters -> feedback, output buffer at n[15]):

  ro_all_ctrl.spice : NO parasitics.  All 32 ROs are topologically identical, so
                      they MUST read the same frequency -> control / self-test.
  ro_all_par.spice  : OpenROAD *D_NET total capacitance lumped to ground on
                      every ring node (nom corner). The resulting spread is a
                      nominal lumped-C prediction of layout-induced bias.

Startup: each RO uses the chip's enable topology -- the shared enable EN is
held low (ring forced to a defined rest state), then pulsed high at t=2 ns. This
injects an edge and favors the intended oscillation mode. (A naive
"tie enable high + .ic kick" start lets uneven loading excite spurious higher-
order modes that read as impossibly high frequencies, so we avoid it.)

Model: only ONE oscillator runs at a time on the chip, so an RO's neighbours are
expected to be static during its measurement. Each net's SPEF *D_NET total is
used as a lumped capacitor to ground. The distributed RC network, explicit
coupling topology, and series wire resistance are not simulated. Transistors
are nominal, so within this approximation the only RO-to-RO difference is the
extracted capacitance. This is a pre-silicon prediction, not a silicon result.

Outputs (next to this script): ro_all_ctrl.spice, ro_all_par.spice,
ro_positions.csv
"""
import re, os, csv, io, sys

HERE  = os.path.dirname(os.path.abspath(__file__))
FIRST = os.path.join(HERE, "first_build")
SPEF  = os.path.join(FIRST, "tt_um_nikodemetrashvili20_ro_puf.nom.spef")
DEFF  = os.path.join(FIRST, "tt_um_nikodemetrashvili20_ro_puf.def")
sys.path.insert(0, os.path.abspath(os.path.join(HERE, "..")))
from pdk_paths import atomic_write_text, sky130_spice_paths, spice_path

NRO, NINV, TAP = 32, 30, 15

def net(i, k):  return f"u_puf.u_core.g_ro_bank[{i}].u_ro.n[{k}]"
def outnet(i):  return f"u_puf.u_core.g_ro_bank[{i}].u_ro.out"

def parse_spef(path):
    num2name, name2cap = {}, {}
    with open(path) as f:
        for line in f:
            m = re.match(r'^\*(\d+)\s+(\S+)\s*$', line)
            if m:
                num2name[m.group(1)] = m.group(2).replace("\\", "")
                continue
            if line.startswith("*D_NET"):
                p = line.split()
                nm = num2name.get(p[1].lstrip("*"))
                if nm:
                    name2cap[nm] = float(p[2])               # picofarads
    return name2cap

def parse_def(path):
    txt = open(path).read()
    um = 1000.0
    mu = re.search(r'UNITS DISTANCE MICRONS\s+(\d+)', txt)
    if mu: um = float(mu.group(1))
    block = re.search(r'^COMPONENTS.*?^END COMPONENTS', txt, re.S | re.M)
    pts = {i: [] for i in range(NRO)}
    if block:
        for chunk in block.group(0).split(";"):
            m = re.search(r'-\s+(\S+)\s+\S+.*?\(\s*(-?\d+)\s+(-?\d+)\s*\)', chunk, re.S)
            if not m:
                continue
            inst = m.group(1).replace("\\", "")
            x, y = int(m.group(2)), int(m.group(3))
            for i in range(NRO):
                if f"g_ro_bank[{i}].u_ro." in inst:
                    pts[i].append((x / um, y / um)); break
    cent = {}
    for i, lst in pts.items():
        if lst:
            cent[i] = (sum(p[0] for p in lst) / len(lst),
                       sum(p[1] for p in lst) / len(lst), len(lst))
    return cent

def cap_f(pf):
    return f"{pf*1e-12:.6e}"

def emit_ro(i, caps):
    p = f"x{i}_"
    L = [f"* --- RO {i} ---",
         # nand2_1 pin order A B VGND VNB VPB VPWR Y ; A=EN(shared), B=n30, Y=n0
         f"X{i}_nand EN {p}n30 0 0 VPWR VPWR {p}n0 sky130_fd_sc_hd__nand2_1"]
    for k in range(1, NINV + 1):
        L.append(f"X{i}_inv{k} {p}n{k-1} 0 0 VPWR VPWR {p}n{k} sky130_fd_sc_hd__inv_1")
    L.append(f"X{i}_buf {p}n{TAP} 0 0 VPWR VPWR {p}out sky130_fd_sc_hd__buf_1")
    if caps:
        for k in range(0, NINV + 1):
            c = caps.get(net(i, k), 0.0)
            if c > 0:
                L.append(f"C{i}_n{k} {p}n{k} 0 {cap_f(c)}")
        co = caps.get(outnet(i), 0.0)
        if co > 0:
            L.append(f"C{i}_out {p}out 0 {cap_f(co)}")
    return L

def header(title):
    corner, cells = sky130_spice_paths()
    return (
        f"* Pre-silicon nominal lumped-C go/no-go: {title}\n"
        "* auto-generated by gen_decks.py -- 32 ring oscillators, enable-started\n"
        f".lib {spice_path(corner)} tt\n"
        f".include {spice_path(cells)}\n"
        ".param SUPPLY=1.8\n"
        "Vdd VPWR 0 {SUPPLY}\n"
        "Ven EN 0 PULSE(0 1.8 2n 50p 50p 1 2)\n"
    )

def build_deck(title, caps):
    out = [header(title)]
    for i in range(NRO):
        out += emit_ro(i, caps)
    out.append("")
    out.append(".save " + " ".join(f"v(x{i}_out)" for i in range(NRO)))
    out.append(".tran 5p 80n")
    out.append(".control")
    out.append("run")
    for i in range(NRO):
        out.append(f"meas tran tp{i} TRIG v(x{i}_out) VAL=0.9 RISE=5 "
                   f"TARG v(x{i}_out) VAL=0.9 RISE=25")
    for i in range(NRO):
        out.append(f"let f{i} = 20 / tp{i}")
    for i in range(NRO):
        out.append(f"print f{i}")
    out.append(".endc")
    out.append(".end")
    return "\n".join(out) + "\n"

def main():
    caps = parse_spef(SPEF)
    cent = parse_def(DEFF)
    missing_centroids = [i for i in range(NRO) if i not in cent]
    if missing_centroids:
        raise RuntimeError(
            "DEF is not a complete placement export; missing RO centroids: "
            + ", ".join(map(str, missing_centroids))
        )

    # Resolve PDK paths and build every output in memory before replacing any
    # tracked artifact. A setup error therefore cannot truncate old evidence.
    ctrl_text = build_deck("CONTROL (no parasitics)", None)
    par_text = build_deck("PARASITIC (nom SPEF)", caps)
    positions = io.StringIO(newline="")
    w = csv.writer(positions, lineterminator="\n")
    w.writerow(["ro", "x_um", "y_um", "ncells", "ring_cap_fF"])
    for i in range(NRO):
        ring = sum(caps.get(net(i, k), 0.0) for k in range(NINV + 1)) * 1000.0
        x, y, n = cent[i]
        w.writerow([i, f"{x:.3f}", f"{y:.3f}", n, f"{ring:.2f}"])

    atomic_write_text(os.path.join(HERE, "ro_all_ctrl.spice"), ctrl_text)
    atomic_write_text(os.path.join(HERE, "ro_all_par.spice"), par_text)
    atomic_write_text(os.path.join(HERE, "ro_positions.csv"), positions.getvalue())

    rings = [sum(caps.get(net(i, k), 0.0) for k in range(NINV + 1)) * 1000.0 for i in range(NRO)]
    mn, mx, av = min(rings), max(rings), sum(rings) / len(rings)
    print(f"SPEF nets parsed: {len(caps)}")
    print("per-RO total RING capacitance (n0..n30), fF: "
          f"min={mn:.1f} max={mx:.1f} mean={av:.1f} spread={mx-mn:.1f} ({100*(mx-mn)/av:.0f}%)")
    print(f"RO placement centroids parsed from DEF: {sum(1 for i in range(NRO) if i in cent)}/{NRO}")
    print("decks regenerated with enable-started startup.")

if __name__ == "__main__":
    main()
