#!/usr/bin/env python3
# SPDX-License-Identifier: Apache-2.0
"""
SILICON Arm B matched frequency : ngspice deck for the HARDENED ro_macro_hard.

Same methodology as gen_decks.py (the Arm A go/no-go), applied to the hardened
macro's own routed netlist + nom SPEF (macro/romacro_final/). Because Arm B is
16 bit-identical GDS copies of this one macro, this single simulation IS the
frequency of every Arm B oscillator -- matched by construction.

One deck, two independent instances driven by the same enable pulse:
  a_*  CONTROL   : no parasitics. Ring is topologically identical to Arm A's,
                   so it MUST read the Arm A control value 633.640 MHz
                   (cross-check that this deck matches the original flow).
  b_*  PARASITIC : every net loaded with its OpenROAD-extracted total cap
                   (nom corner) from the macro SPEF. This is the number.

Netlist mirrored from macro/romacro_final/nl/ro_macro_hard.nl.v:
  en -> clkdlybuf4s25_1 (input1) -> net1 -> NAND.A ; ring: nand2_1 + 30x inv_1,
  feedback n[30]->NAND.B ; buf_1 taps n[15] -> net2 -> clkdlybuf4s25_1
  (output2) -> out. Delay buffers are OUTSIDE the loop (delay only, no effect
  on period). Pin orders verified from macro/romacro_final/spice (magic ext):
  nand2_1 A B VGND VNB VPB VPWR Y ; inv_1/buf_1/clkdlybuf4s25_1
  A VGND VNB VPB VPWR X|Y.
Startup, models, corner, cap-lumping, measurement (rise 5 -> rise 25, f=20/tp)
all identical to gen_decks.py.

Output: ro_macro_matched.spice (run in WSL:
  ngspice -b ro_macro_matched.spice -o macro_out.txt )
"""
import re, os

HERE  = os.path.dirname(os.path.abspath(__file__))
PROJ  = os.path.abspath(os.path.join(HERE, "..", "..", ".."))
SPEF  = os.path.join(PROJ, "macro", "romacro_final", "spef", "nom",
                     "ro_macro_hard.nom.spef")
NINV, TAP = 30, 15

def parse_spef(path):
    num2name, name2cap = {}, {}
    with open(path) as f:
        for line in f:
            m = re.match(r'^\*(\d+)\s+(\S+)\s*$', line)
            if m:
                num2name[m.group(1)] = m.group(2).replace("\\", "")
                continue
            if line.startswith("*D_NET"):
                p = line.split()
                nm = num2name.get(p[1].lstrip("*"))
                if nm:
                    name2cap[nm] = float(p[2])               # picofarads
    return name2cap

def cap_f(pf):
    return f"{pf*1e-12:.6e}"

def emit_ro(tag, caps):
    """One complete macro instance. tag='a' control / 'b' parasitic."""
    p = f"{tag}_"
    L = [f"* --- {'CONTROL (no parasitics)' if caps is None else 'PARASITIC (macro nom SPEF)'} ---",
         f"X{tag}_dlyin  EN 0 0 VPWR VPWR {p}net1 sky130_fd_sc_hd__clkdlybuf4s25_1",
         f"X{tag}_nand   {p}net1 {p}n{NINV} 0 0 VPWR VPWR {p}n0 sky130_fd_sc_hd__nand2_1"]
    for k in range(1, NINV + 1):
        L.append(f"X{tag}_inv{k} {p}n{k-1} 0 0 VPWR VPWR {p}n{k} sky130_fd_sc_hd__inv_1")
    L.append(f"X{tag}_buf    {p}n{TAP} 0 0 VPWR VPWR {p}net2 sky130_fd_sc_hd__buf_1")
    L.append(f"X{tag}_dlyout {p}net2 0 0 VPWR VPWR {p}out sky130_fd_sc_hd__clkdlybuf4s25_1")
    if caps:
        for k in range(0, NINV + 1):
            c = caps.get(f"u_ro.n[{k}]", 0.0)
            if c > 0:
                L.append(f"C{tag}_n{k} {p}n{k} 0 {cap_f(c)}")
        for spefname, localnet in (("net1", f"{p}net1"), ("net2", f"{p}net2"),
                                   ("out", f"{p}out")):
            c = caps.get(spefname, 0.0)
            if c > 0:
                L.append(f"C{tag}_{spefname} {localnet} 0 {cap_f(c)}")
        # 'en' is a macro-boundary pin net; on chip it is driven externally --
        # load it on the control-side of the input delay buffer anyway for
        # completeness (outside the loop, no effect on period).
        c = caps.get("en", 0.0)
        if c > 0:
            L.append(f"C{tag}_en EN 0 {cap_f(c)}")
    return L

HEADER = (
    "* SILICON Arm B matched frequency : hardened ro_macro_hard, nom SPEF\n"
    "* auto-generated by gen_macro_deck.py -- enable-started, same flow as gono\n"
    ".lib /home/pc/pdks/sky130A/libs.tech/ngspice/sky130.lib.spice tt\n"
    ".include /home/pc/pdks/sky130A/libs.ref/sky130_fd_sc_hd/spice/sky130_fd_sc_hd.spice\n"
    ".param SUPPLY=1.8\n"
    "Vdd VPWR 0 {SUPPLY}\n"
    "Ven EN 0 PULSE(0 1.8 2n 50p 50p 1 2)\n")

def main():
    caps = parse_spef(SPEF)
    ring = sum(caps.get(f"u_ro.n[{k}]", 0.0) for k in range(NINV + 1)) * 1000.0
    missing = [k for k in range(NINV + 1) if f"u_ro.n[{k}]" not in caps]

    out = [HEADER]
    out += emit_ro("a", None)
    out += emit_ro("b", caps)
    out.append("")
    out.append(".save v(a_out) v(b_out)")
    out.append(".tran 5p 80n")
    out.append(".control")
    out.append("run")
    for t in ("a", "b"):
        out.append(f"meas tran tp_{t} TRIG v({t}_out) VAL=0.9 RISE=5 "
                   f"TARG v({t}_out) VAL=0.9 RISE=25")
    out.append("let f_a = 20 / tp_a")
    out.append("let f_b = 20 / tp_b")
    out.append("print f_a")
    out.append("print f_b")
    out.append(".endc")
    out.append(".end")

    deck = os.path.join(HERE, "ro_macro_matched.spice")
    with open(deck, "w") as f:
        f.write("\n".join(out) + "\n")

    print(f"SPEF nets parsed: {len(caps)}  (expect 35)")
    print(f"ring nets n[0..30] found: {NINV+1-len(missing)}/31  missing={missing}")
    print(f"macro RING capacitance (n0..n30): {ring:.2f} fF  "
          f"(Arm A flat build was 7.4-17.8 fF)")
    print(f"deck written: {deck}")

if __name__ == "__main__":
    main()
