#!/usr/bin/env python3
# SPDX-License-Identifier: Apache-2.0
"""
SILICON Stage 3: decks for the DUAL-ARM chip build (Arm A, 16 oscillators).
Derived mechanically from gen_decks.py (32-RO version); only NRO, the input
paths, and the output names differ. Arm B is not in these decks: its 16 copies
are one sealed macro, measured once in ro_macro_matched.spice (569.5 MHz).

Two combined decks, each with all 32 ring oscillators wired exactly as on
silicon (enable NAND -> 30 inverters -> feedback, output buffer tapping n[15]):

  ro_all_ctrl.spice : NO parasitics.  All 32 ROs are topologically identical, so
                      they MUST read the same frequency -> control / self-test.
  ro_all_par.spice  : real OpenROAD-extracted capacitance on every ring node
                      (nom corner). Spread across ROs = layout-induced bias.

Startup: each RO is started the way the chip does it -- the shared enable EN is
held low (ring forced to a defined rest state), then pulsed high at t=2 ns. This
injects a single edge and guarantees the fundamental oscillation mode. (A naive
"tie enable high + .ic kick" start lets uneven loading excite spurious higher-
order modes that read as impossibly high frequencies, so we avoid it.)

Model: only ONE oscillator runs at a time on the chip, so an RO's neighbours are
static during its measurement and their coupling cap acts as fixed grounded
load. Each net's SPEF *D_NET line pre-sums ground + coupling cap, so we hang
that total as a lumped cap to ground (farads, plain sci notation). Series wire R
(~30 ohm) shifts stage delay <0.1% and is omitted. Transistors are nominal, so
the ONLY RO-to-RO difference is layout parasitics.

Outputs (next to this script): ro_all_ctrl.spice, ro_all_par.spice,
ro_positions.csv
"""
import re, os, csv

HERE  = os.path.dirname(os.path.abspath(__file__))
PROJ  = os.path.abspath(os.path.join(HERE, "..", "..", ".."))
FINAL = os.path.join(PROJ, "dualarm", "build_debug")
SPEF  = os.path.join(FINAL, "tt_um_nikodemetrashvili20_ro_puf.nom.spef")
DEFF  = os.path.join(FINAL, "tt_um_nikodemetrashvili20_ro_puf.def")

NRO, NINV, TAP = 16, 30, 15

def net(i, k):  return f"u_puf.u_core.g_ro_bank[{i}].u_ro.n[{k}]"
def outnet(i):  return f"u_puf.u_core.g_ro_bank[{i}].u_ro.out"

def parse_spef(path):
    num2name, name2cap = {}, {}
    with open(path) as f:
        for line in f:
            m = re.match(r'^\*(\d+)\s+(\S+)\s*$', line)
            if m:
                num2name[m.group(1)] = m.group(2).replace("\\", "")
                continue
            if line.startswith("*D_NET"):
                p = line.split()
                nm = num2name.get(p[1].lstrip("*"))
                if nm:
                    name2cap[nm] = float(p[2])               # picofarads
    return name2cap

def parse_def(path):
    txt = open(path).read()
    um = 1000.0
    mu = re.search(r'UNITS DISTANCE MICRONS\s+(\d+)', txt)
    if mu: um = float(mu.group(1))
    block = re.search(r'^COMPONENTS.*?^END COMPONENTS', txt, re.S | re.M)
    pts = {i: [] for i in range(NRO)}
    if block:
        for chunk in block.group(0).split(";"):
            m = re.search(r'-\s+(\S+)\s+\S+.*?\(\s*(-?\d+)\s+(-?\d+)\s*\)', chunk, re.S)
            if not m:
                continue
            inst = m.group(1).replace("\\", "")
            x, y = int(m.group(2)), int(m.group(3))
            for i in range(NRO):
                if f"g_ro_bank[{i}].u_ro." in inst:
                    pts[i].append((x / um, y / um)); break
    cent = {}
    for i, lst in pts.items():
        if lst:
            cent[i] = (sum(p[0] for p in lst) / len(lst),
                       sum(p[1] for p in lst) / len(lst), len(lst))
    return cent

def cap_f(pf):
    return f"{pf*1e-12:.6e}"

def emit_ro(i, caps):
    p = f"x{i}_"
    L = [f"* --- RO {i} ---",
         # nand2_1 pin order A B VGND VNB VPB VPWR Y ; A=EN(shared), B=n30, Y=n0
         f"X{i}_nand EN {p}n30 0 0 VPWR VPWR {p}n0 sky130_fd_sc_hd__nand2_1"]
    for k in range(1, NINV + 1):
        L.append(f"X{i}_inv{k} {p}n{k-1} 0 0 VPWR VPWR {p}n{k} sky130_fd_sc_hd__inv_1")
    L.append(f"X{i}_buf {p}n{TAP} 0 0 VPWR VPWR {p}out sky130_fd_sc_hd__buf_1")
    if caps:
        for k in range(0, NINV + 1):
            c = caps.get(net(i, k), 0.0)
            if c > 0:
                L.append(f"C{i}_n{k} {p}n{k} 0 {cap_f(c)}")
        co = caps.get(outnet(i), 0.0)
        if co > 0:
            L.append(f"C{i}_out {p}out 0 {cap_f(co)}")
    return L

HEADER = (
    "* SILICON go/no-go : {title}\n"
    "* auto-generated by gen_decks.py -- 32 ring oscillators, enable-started\n"
    ".lib /home/pc/pdks/sky130A/libs.tech/ngspice/sky130.lib.spice tt\n"
    ".include /home/pc/pdks/sky130A/libs.ref/sky130_fd_sc_hd/spice/sky130_fd_sc_hd.spice\n"
    ".param SUPPLY=1.8\n"
    "Vdd VPWR 0 {{SUPPLY}}\n"
    "Ven EN 0 PULSE(0 1.8 2n 50p 50p 1 2)\n")     # hold low, release at 2 ns

def build_deck(title, caps):
    out = [HEADER.format(title=title)]
    for i in range(NRO):
        out += emit_ro(i, caps)
    out.append("")
    out.append(".save " + " ".join(f"v(x{i}_out)" for i in range(NRO)))
    out.append(".tran 5p 80n")
    out.append(".control")
    out.append("run")
    for i in range(NRO):
        out.append(f"meas tran tp{i} TRIG v(x{i}_out) VAL=0.9 RISE=5 "
                   f"TARG v(x{i}_out) VAL=0.9 RISE=25")
    for i in range(NRO):
        out.append(f"let f{i} = 20 / tp{i}")
    for i in range(NRO):
        out.append(f"print f{i}")
    out.append(".endc")
    out.append(".end")
    return "\n".join(out) + "\n"

def main():
    caps = parse_spef(SPEF)
    cent = parse_def(DEFF)

    with open(os.path.join(HERE, "dualarm_ctrl.spice"), "w") as f:
        f.write(build_deck("CONTROL (no parasitics)", None))
    with open(os.path.join(HERE, "dualarm_par.spice"), "w") as f:
        f.write(build_deck("PARASITIC (nom SPEF)", caps))

    with open(os.path.join(HERE, "dualarm_positions.csv"), "w", newline="\n") as f:
        w = csv.writer(f, lineterminator="\n"); w.writerow(["ro", "x_um", "y_um", "ncells", "ring_cap_fF"])
        for i in range(NRO):
            ring = sum(caps.get(net(i, k), 0.0) for k in range(NINV + 1)) * 1000.0
            x, y, n = cent.get(i, (float("nan"), float("nan"), 0))
            w.writerow([i, f"{x:.3f}", f"{y:.3f}", n, f"{ring:.2f}"])

    rings = [sum(caps.get(net(i, k), 0.0) for k in range(NINV + 1)) * 1000.0 for i in range(NRO)]
    mn, mx, av = min(rings), max(rings), sum(rings) / len(rings)
    print(f"SPEF nets parsed: {len(caps)}")
    print("per-RO total RING capacitance (n0..n30), fF: "
          f"min={mn:.1f} max={mx:.1f} mean={av:.1f} spread={mx-mn:.1f} ({100*(mx-mn)/av:.0f}%)")
    print(f"RO placement centroids parsed from DEF: {sum(1 for i in range(NRO) if i in cent)}/{NRO}")
    print("decks regenerated with enable-started startup.")

if __name__ == "__main__":
    main()
