#!/usr/bin/env python3
# SPDX-FileCopyrightText: 2026 Nikoloz Demetrashvili
# SPDX-License-Identifier: Apache-2.0
"""Offline checks on the Arm B per-instance decks at ss and ff, hardware item 6.

The per-instance deck already took a --corner argument when it was written for
item 8, and only tt was ever run. Before spending several hours of simulator time
on the other two I wanted to know that the corner argument does what its name
says, and that the two constants the report leans on are the archived numbers and
not numbers I typed from memory.

Nothing here needs a PDK, a simulator or a network. The design files it reads are
the ones already in the repository, and the two SKY130 paths are stubbed, because
what is being checked is which lines of the deck a corner changes, not what the
transistors in them do.

    python3 test_instance_corners.py
"""

import os
import re
import statistics as st
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.abspath(os.path.join(HERE, "..", "..", ".."))
BUILD = os.path.join(ROOT, "dualarm", "build_current")

sys.path.insert(0, HERE)
sys.path.insert(0, os.path.abspath(os.path.join(HERE, "..")))

import gen_instance_decks as G          # noqa: E402
from analyze_instance import ARM_A_DISPERSION, CONTROL_MHZ  # noqa: E402

CORNERS = ("tt", "ss", "ff")
ARCHIVED = {
    "tt": ("dualarm_ctrl_out.txt", "dualarm_par_out.txt"),
    "ss": ("dualarm_ctrl_ss_out.txt", "dualarm_par_ss_out.txt"),
    "ff": ("dualarm_ctrl_ff_out.txt", "dualarm_par_ff_out.txt"),
}

# The pin order the deck is built with here. It is not read from the PDK, and it
# is not meant to be right: the three decks are compared against each other, so
# whatever it says cancels. Nothing generated by this file may be simulated.
STUB_PINS = {
    "sky130_fd_sc_hd__inv_1": ["A", "VGND", "VNB", "VPB", "VPWR", "Y"],
    "sky130_fd_sc_hd__buf_1": ["A", "VGND", "VNB", "VPB", "VPWR", "X"],
    "sky130_fd_sc_hd__nand2_1": ["A", "B", "VGND", "VNB", "VPB", "VPWR", "Y"],
    "sky130_fd_sc_hd__clkdlybuf4s25_1": ["A", "VGND", "VNB", "VPB", "VPWR", "X"],
}

results = []


def check(name, ok, detail=""):
    results.append((name, bool(ok), detail))


def arm_a(path):
    """The sixteen Arm A frequencies in MHz from an archived go/no-go log."""
    txt = open(os.path.join(BUILD, path), errors="ignore").read()
    d = {n: float(v) / 1e6
         for n, v in re.findall(r'^(f\d+)\s*=\s*(-?[0-9.eE+-]+)', txt, re.M)}
    return [d["f%d" % i] for i in range(16)]


def ptp_percent(vals):
    m = st.mean(vals)
    return 100 * (max(vals) - min(vals)) / m


# ------------------------------------------------------- the two constant tables

for c in CORNERS:
    ctrl = arm_a(ARCHIVED[c][0])
    check("control %s matches the archived Arm A control log" % c,
          abs(CONTROL_MHZ[c] - ctrl[0]) < 5e-4,
          "table %.4f, log %.4f" % (CONTROL_MHZ[c], ctrl[0]))
    check("the %s control log really is sixteen identical rings" % c,
          max(ctrl) == min(ctrl), "%.4f to %.4f" % (min(ctrl), max(ctrl)))

for c in ("ss", "ff"):
    got = ptp_percent(arm_a(ARCHIVED[c][1]))
    check("Arm A dispersion at %s matches the archived parasitic log" % c,
          abs(ARM_A_DISPERSION[c][0] - got) < 5e-3,
          "table %.3f, log %.3f" % (ARM_A_DISPERSION[c][0], got))

# tt is the one corner where a distributed Arm A run exists, so the report uses
# it there. It is the larger of the two models, which is worth stating out loud:
# the ss and ff comparisons are made against a smaller number than tt's, so if
# anything they are the harder ones to pass.
lumped_tt = ptp_percent(arm_a(ARCHIVED["tt"][1]))
check("tt uses the distributed figure and it is above the lumped one",
      ARM_A_DISPERSION["tt"][0] > lumped_tt,
      "distributed %.2f against lumped %.3f" % (ARM_A_DISPERSION["tt"][0], lumped_tt))
check("the three Arm A spreads agree within a tenth of a point",
      max(ptp_percent(arm_a(ARCHIVED[c][1])) for c in CORNERS)
      - min(ptp_percent(arm_a(ARCHIVED[c][1])) for c in CORNERS) < 0.11,
      "%.3f, %.3f, %.3f" % tuple(ptp_percent(arm_a(ARCHIVED[c][1])) for c in CORNERS))

# --------------------------------------------------------------- the transient window

for c in CORNERS:
    need = G.last_edge_ns(c, 25)
    have = G.CORNERS[c]["tstop_ns"]
    check("the default %s window holds the twenty-fifth edge" % c,
          have >= 1.2 * need, "%g ns against %.1f needed" % (have, need))
    smoke = 20 if c != "ss" else 60
    check("the %s smoke window holds the seventh edge" % c,
          smoke >= G.last_edge_ns(c, 7),
          "%g ns against %.1f needed" % (smoke, G.last_edge_ns(c, 7)))

check("the slow corner needs a longer window than the fast one",
      G.last_edge_ns("ss", 25) > G.last_edge_ns("tt", 25) > G.last_edge_ns("ff", 25),
      "%.1f, %.1f, %.1f ns" % tuple(G.last_edge_ns(c, 25) for c in CORNERS))

refused = False
try:
    G.main(["--corner", "ss", "--tstop-ns", "80", "--output-dir", "/tmp/never"])
except SystemExit as exc:
    refused = "should not arrive until" in str(exc)
check("an ss run in a tt-sized window is refused before it is written", refused)


# ------------------------------------------------------------- what a corner changes

def deck(corner_name):
    """One deck, built through the real code path with the PDK paths stubbed."""
    cn = dict(G.CORNERS[corner_name])
    cn["step_ps"] = 1
    cn["first_edge"], cn["last_edge"] = 5, 25
    insts, drivers, loads = G.read_netlist(G.NETLIST)
    topnames, topnets = G.parse_spef_full(G.TOP_SPEF)
    text, _, _ = G.build(cn, order, insts, drivers, loads, topnames, topnets,
                         G.parse_spef_total(G.TOP_SPEF),
                         G.parse_spef_total(G.MACRO_SPEF))
    return text


order = dict(STUB_PINS)
for cell in G.ENABLE_DRIVERS:
    pins = [p for p in ("A", "B", "C", "D")][:1 + len(G.ENABLE_DRIVERS[cell]["sides"])]
    order[cell] = pins + ["VGND", "VNB", "VPB", "VPWR", "X"]
for cell, table in G.CELLS.items():
    pins = sorted({p for p in table} | {s for sides in table.values() for s in sides})
    order[cell] = pins + ["VGND", "VNB", "VPB", "VPWR", "X"]

G.sky130_spice_paths = lambda: ("/stub/sky130.lib.spice",
                                "/stub/sky130_fd_sc_hd.spice")

decks = {c: deck(c) for c in CORNERS}


def body(text):
    """The circuit itself: everything between the control comment and .save."""
    return text.split("* --- control", 1)[1].split("\n.save", 1)[0]


check("the circuit is the same at all three corners",
      body(decks["tt"]) == body(decks["ss"]) == body(decks["ff"]),
      "%d characters" % len(body(decks["tt"])))

ALLOWED = (".lib ", ".temp ", ".param SUPPLY", "Vone ", "Ven ", ".tran ", "meas tran ")
for c in ("ss", "ff"):
    a, b = decks["tt"].splitlines(), decks[c].splitlines()
    changed = set(a).symmetric_difference(b)
    stray = sorted(l for l in changed if not l.startswith(ALLOWED))
    check("tt against %s changes only the corner lines" % c, not stray,
          "%d lines differ, none unexpected" % len(changed) if not stray
          else "unexpected: " + "; ".join(stray[:3]))

for c in CORNERS:
    want = G.CORNERS[c]["supply"] / 2.0
    thresholds = {float(v) for v in
                  re.findall(r'meas tran (?:tp|tq|hi|hx|dr|df)_\w+ TRIG \S+ VAL=([0-9.]+)',
                             decks[c])}
    check("the %s measurement threshold follows its supply" % c,
          thresholds == {want}, "%s against %g" % (sorted(thresholds), want))

check("the fast corner is the only one that raises the supply above 1.8",
      G.CORNERS["ff"]["supply"] > 1.8 > G.CORNERS["ss"]["supply"])


# ------------------------------------------------------------------------ report

width = max(len(n) for n, _, _ in results)
bad = 0
for name, ok, detail in results:
    bad += not ok
    print("  %-5s %-*s %s" % ("ok" if ok else "FAIL", width, name, detail))
print("%d checks, %d failed" % (len(results), bad))
sys.exit(1 if bad else 0)
