#!/usr/bin/env python3
# SPDX-FileCopyrightText: 2026 Nikoloz Demetrashvili
# SPDX-License-Identifier: Apache-2.0
"""
First-order Monte Carlo mismatch-sensitivity study for the matched arm, v2.

Why v2, and what v1 got wrong: sky130's mismatch parameters are GLOBAL
.param statements, so ngspice draws ONE value per run, shared by every
transistor of a given model. A 16-oscillator deck therefore produced 16
identical frequencies per run (v1 measured exactly that: within-chip sigma
0.000, confirmed against the PDK source). The v2 approach uses the sharing
instead of fighting it. One oscillator, mismatch switch on, process switch
off: each run shifts all 31 in-loop nfets together and all 31 pfets
together. Under the simplifying assumptions of equal per-stage sensitivity
and independent device draws, the common-draw sigma gives a first-order
independent-per-device estimate by scaling with sqrt(31):

    sigma_per_ring = sigma_common / sqrt(31)

analyze_mc.py applies that approximation and builds virtual chips from the
derived sigma. Those virtual chips are a model sanity check, not validation
of silicon entropy, reliability, uniqueness, or attack resistance.
One oscillator per run is also 10x faster than v1 and avoids the
convergence crash an extreme process draw caused in v1 (died at run 17).

Run: python3 ../run_ngspice.py mc_matched.spice --log mc_out.txt (~2-4 min)
Then:      python3 analyze_mc.py mc_out.txt
"""
import re, os, sys

HERE  = os.path.dirname(os.path.abspath(__file__))
PROJ  = os.path.abspath(os.path.join(HERE, "..", "..", ".."))
sys.path.insert(0, os.path.dirname(HERE))
from pdk_paths import atomic_write_text, sky130_spice_paths, spice_path
SPEF  = os.path.join(PROJ, "macro", "romacro_final", "spef", "nom",
                     "ro_macro_hard.nom.spef")
NINV, TAP = 30, 15
MC_RUNS = 40
SEED    = 42

def parse_spef(path):
    num2name, name2cap = {}, {}
    with open(path) as f:
        for line in f:
            m = re.match(r'^\*(\d+)\s+(\S+)\s*$', line)
            if m:
                num2name[m.group(1)] = m.group(2).replace("\\", "")
                continue
            if line.startswith("*D_NET"):
                p = line.split()
                nm = num2name.get(p[1].lstrip("*"))
                if nm:
                    name2cap[nm] = float(p[2])
    return name2cap

def cap_f(pf):
    return f"{pf*1e-12:.6e}"

def emit_ro(caps):
    """The macro oscillator, identical to gen_macro_deck.py's parasitic
    instance: same ring, same delay buffers, same lumped caps."""
    p = "m0_"
    L = ["* --- the matched oscillator (macro layout parasitics) ---",
         f"X0_dlyin  EN 0 0 VPWR VPWR {p}net1 sky130_fd_sc_hd__clkdlybuf4s25_1",
         f"X0_nand   {p}net1 {p}n{NINV} 0 0 VPWR VPWR {p}n0 sky130_fd_sc_hd__nand2_1"]
    for k in range(1, NINV + 1):
        L.append(f"X0_inv{k} {p}n{k-1} 0 0 VPWR VPWR {p}n{k} sky130_fd_sc_hd__inv_1")
    L.append(f"X0_buf    {p}n{TAP} 0 0 VPWR VPWR {p}net2 sky130_fd_sc_hd__buf_1")
    L.append(f"X0_dlyout {p}net2 0 0 VPWR VPWR {p}out sky130_fd_sc_hd__clkdlybuf4s25_1")
    for k in range(0, NINV + 1):
        c = caps.get(f"u_ro.n[{k}]", 0.0)
        if c > 0:
            L.append(f"C0_n{k} {p}n{k} 0 {cap_f(c)}")
    for spefname, localnet in (("net1", f"{p}net1"), ("net2", f"{p}net2"),
                               ("out", f"{p}out")):
        c = caps.get(spefname, 0.0)
        if c > 0:
            L.append(f"C0_{spefname} {localnet} 0 {cap_f(c)}")
    return L

def main():
    caps = parse_spef(SPEF)
    model, cells = sky130_spice_paths()
    ring = sum(caps.get(f"u_ro.n[{k}]", 0.0) for k in range(NINV + 1)) * 1000.0

    out = [
        "* First-order Monte Carlo sensitivity: mismatch-only common draws",
        "* auto-generated by gen_mc_deck.py; not a silicon entropy validation",
        f".lib {spice_path(model)} tt",
        ".param MC_MM_SWITCH=1",
        ".param MC_PR_SWITCH=0",
        f".include {spice_path(cells)}",
        ".param SUPPLY=1.8",
        "Vdd VPWR 0 {SUPPLY}",
        "Ven EN 0 PULSE(0 1.8 2n 50p 50p 1 2)",
        "",
    ]
    out += emit_ro(caps)
    out.append("")
    out.append(".save v(m0_out)")
    out.append(".tran 5p 80n")
    out.append(".control")
    out.append(f"set rndseed={SEED}")
    out.append("let mc_i = 0")
    out.append(f"dowhile mc_i < {MC_RUNS}")
    out.append("  reset")
    out.append("  run")
    out.append("  meas tran tp0 TRIG v(m0_out) VAL=0.9 RISE=5 "
               "TARG v(m0_out) VAL=0.9 RISE=25")
    out.append("  let f0 = 20 / tp0")
    out.append("  print f0")
    out.append("  let mc_i = mc_i + 1")
    out.append("end")
    out.append(".endc")
    out.append(".end")

    deck = os.path.join(HERE, "mc_matched.spice")
    atomic_write_text(deck, "\n".join(out) + "\n")
    print(f"deck written: {deck}")
    print(f"macro ring cap {ring:.2f} fF, 1 oscillator, {MC_RUNS} runs, seed {SEED}")

if __name__ == "__main__":
    main()
