# SPDX-FileCopyrightText: 2026 Nikoloz Demetrashvili
# SPDX-License-Identifier: Apache-2.0
#
# Unlike the other two, this one is Tiny Tapeout's template file essentially
# untouched: the only changes are the checkout action version and the shuttle
# tag on tt-gds-action. The template is Apache 2.0 and carries no copyright
# line of its own. The line above is here because the licence audit asks every
# .yaml in the tree for one, and it claims nothing beyond those two bumps.

name: fpga

on:
  push:
    # Comment out (or remove) the following line to run the FPGA workflow on every push:
    branches: none
  workflow_dispatch:

jobs:
  fpga:
    runs-on: ubuntu-24.04
    steps:
      - name: checkout repo
        uses: actions/checkout@v6
        with:
          submodules: recursive

      - name: FPGA bitstream for TT ASIC Sim (ICE40UP5K)
        uses: TinyTapeout/tt-gds-action/fpga/ice40up5k@ttsky26c
